[package]
name = "promethius"
version = "0.1.0"
edition = "2021"

[dependencies]
small_derive_deref = "0.1.3"
event_deriver = { path = "./event_deriver" }
wgpu = "22.1.0"
winit = "0.30.5"
hecs = "0.10.5"
